/**
 * Academic Paper Validation — Data Models
 *
 * Types that support the academic traceability system: connecting each Issue
 * generated by detectors to the scientific paper that underpins it, and
 * validating YAML contract coverage against detector implementations.
 */

/**
 * Reference to an academic paper that underpins a detection rule.
 * Attached to Issues via the `academicReference` optional field.
 */
export interface AcademicReference {
  /** Paper identifier, e.g. "IEEE-SP-2024" */
  paperId: string;
  /** Full paper title */
  title: string;
  /** Conference or journal where the paper was published, e.g. "IEEE S&P" */
  venue: string;
  /** Publication year, e.g. 2024 */
  year: number;
  /** Rule identifier within the YAML contract, e.g. "R001" */
  ruleId: string;
  /** Fact identifiers associated with this rule, e.g. ["F001", "F002"] */
  factIds: string[];
  /** Optional DOI (Digital Object Identifier) */
  doi?: string;
  /** Optional URL to the paper */
  url?: string;
}

/**
 * Traceability entry for a single rule or fact in a YAML contract.
 * Records which source file implements it, which test file covers it,
 * and the current implementation status.
 */
export interface TraceabilityEntry {
  /** Relative path to the TypeScript implementation file */
  implementation: string;
  /** Relative path to the test file */
  tests: string;
  /** Current implementation status */
  status: 'implemented' | 'pending' | 'not_applicable';
}

/**
 * A rule entry within a YAML contract (`rules[]`).
 */
export interface YAMLRule {
  /** Rule identifier, e.g. "R001" */
  id: string;
  /** Human-readable principle the rule enforces */
  principle: string;
  /** Fact IDs this rule is derived from */
  derived_from: string[];
  /** Action to take when the rule fires */
  action: string;
  /** Name of the detector that implements this rule, e.g. "SlopsquatDetector" */
  detector_name?: string;
  /** Reference to the paper ID in the registry, e.g. "IEEE-SP-2024" */
  paperRef?: string;
  /** Rule priority */
  priority: 'high' | 'medium' | 'low';
}

/**
 * A fact entry within a YAML contract (`facts[]`).
 */
export interface YAMLFact {
  /** Fact identifier, e.g. "F001" */
  id: string;
  /** Human-readable statement of the fact */
  statement: string;
  /** Fact category/type */
  type: string;
  /** Why this fact is relevant to the detector */
  relevance: string;
  /** Optional location reference (e.g. section in the paper) */
  location?: string;
}

/**
 * Represents a parsed YAML contract file from `knowledge-base/`.
 * Structure: source → facts → patterns → rules → cases → traceability.
 */
export interface ContratoYAML {
  /** Paper source metadata */
  source: {
    title: string;
    authors: string;
    year: number;
    url?: string;
    doi?: string;
  };
  /** Extracted facts from the paper */
  facts: YAMLFact[];
  /** Optional patterns section */
  patterns?: unknown[];
  /** Detection rules derived from the paper */
  rules: YAMLRule[];
  /** Optional case studies section */
  cases?: unknown[];
  /** Traceability map: RuleId/FactId → TraceabilityEntry */
  traceability?: Record<string, TraceabilityEntry>;
  /** Optional metadata */
  metadata?: Record<string, unknown>;
}

/**
 * Coverage summary for a single YAML contract.
 */
export interface ContractCoverage {
  /** Paper identifier this contract belongs to */
  paperId: string;
  /** Path to the contract file */
  contractFile: string;
  /** Total number of rules in the contract */
  totalRules: number;
  /** Total number of facts in the contract */
  totalFacts: number;
  /** Number of rules/facts with status "implemented" */
  implementedCount: number;
  /** Number of rules/facts with status "pending" */
  pendingCount: number;
  /** Number of rules/facts with no traceability entry at all */
  missingCount: number;
  /** IDs of rules/facts that have no implementation registered */
  gaps: string[];
}

/**
 * Aggregated coverage report across all YAML contracts.
 * Generated by `CoverageValidator.validate()`.
 */
export interface CoverageReport {
  /** ISO 8601 timestamp of when the report was generated */
  generatedAt: string;
  /** Per-contract coverage details */
  contracts: ContractCoverage[];
  /** Total rules across all contracts */
  totalRules: number;
  /** Total facts across all contracts */
  totalFacts: number;
  /** Total rules+facts with status "implemented" */
  totalImplemented: number;
  /** Global coverage percentage, rounded to 1 decimal place */
  coveragePercentage: number;
}

/**
 * A single entry in the paper registry (`knowledge-base/registry.yaml`).
 */
export interface PaperRegistryEntry {
  /** Unique paper identifier, e.g. "IEEE-SP-2024" */
  paperId: string;
  /** Full paper title */
  title: string;
  /** Conference or journal, e.g. "IEEE S&P" */
  venue: string;
  /** Publication year */
  year: number;
  /** Path to the YAML contract file, relative to `knowledge-base/` */
  contractFile: string;
  /** Names of detectors that implement rules from this paper */
  detectors: string[];
}

/**
 * The full paper registry, as parsed from `knowledge-base/registry.yaml`.
 */
export interface PaperRegistry {
  papers: PaperRegistryEntry[];
}
