/**
 * SandboxDetector Tests
 */

import { describe, it, expect, beforeEach } from 'vitest';
import { SandboxDetector, createSandboxDetector } from '../../src/detectors/SandboxDetector.js';

describe('SandboxDetector', () => {
  let detector: SandboxDetector;

  beforeEach(() => {
    detector = createSandboxDetector();
  });

  describe('detect', () => {
    it('should detect AI Studio from @google/generative-ai import', () => {
      const code = "import { create } from '@google/generative-ai';";
      
      const type = detector.detect(code);
      
      expect(type).toBe('ai-studio');
    });

    it('should detect AI Studio from @google/ai-protos import', () => {
      const code = "import { GenerateContentRequest } from '@google/ai-protos';";
      
      const type = detector.detect(code);
      
      expect(type).toBe('ai-studio');
    });

    it('should detect AI Studio from gemini references', () => {
      const code = "const model = new GeminiModel('gemini-pro');";
      
      const type = detector.detect(code);
      
      expect(type).toBe('ai-studio');
    });

    it('should detect AI Studio from google.ai.generativelanguage API', () => {
      const code = "import { generativeLanguage } from 'google.ai.generativelanguage';";
      
      const type = detector.detect(code);
      
      expect(type).toBe('ai-studio');
    });

    it('should detect Bolt.new', () => {
      const code = "// Generated by bolt.new";
      
      const type = detector.detect(code);
      
      expect(type).toBe('bolt.new');
    });

    it('should detect Replit from @replit packages', () => {
      const code = "import { database } from '@replit/database';";
      
      const type = detector.detect(code);
      
      expect(type).toBe('replit');
    });

    it('should detect Replit from internal packages', () => {
      const code = "import { replitAuth } from 'replit/auth';";
      
      const type = detector.detect(code);
      
      expect(type).toBe('replit');
    });

    it('should detect CodeSandbox', () => {
      const code = "// Running in codesandbox";
      
      const type = detector.detect(code);
      
      expect(type).toBe('codesandbox');
    });

    it('should detect StackBlitz', () => {
      const code = "// Running on stackblitz";
      
      const type = detector.detect(code);
      
      expect(type).toBe('stackblitz');
    });

    it('should return unknown when no pattern matches', () => {
      const code = "import React from 'react';";
      
      const type = detector.detect(code);
      
      expect(type).toBe('unknown');
    });
  });

  describe('detectAll', () => {
    it('should detect all sandbox types in mixed code', () => {
      const code = `
        import { create } from '@google/generative-ai';
        import { database } from '@replit/database';
        // bolt.new reference
      `;
      
      const types = detector.detectAll(code);
      
      expect(types).toContain('ai-studio');
      expect(types).toContain('replit');
      expect(types).toContain('bolt.new');
    });

    it('should return [unknown] when no patterns match', () => {
      const code = "import React from 'react';";
      
      const types = detector.detectAll(code);
      
      expect(types).toEqual(['unknown']);
    });
  });

  describe('detectDetailed', () => {
    it('should return detailed detection results', () => {
      const code = "import { create } from '@google/generative-ai';";
      
      const results = detector.detectDetailed(code);
      
      expect(results).toHaveLength(1);
      expect(results[0].type).toBe('ai-studio');
      expect(results[0].description).toBeTruthy();
      expect(typeof results[0].description).toBe('string');
    });

    it('should return multiple detailed results', () => {
      const code = `
        import { create } from '@google/generative-ai';
        import { database } from '@replit/database';
      `;
      
      const results = detector.detectDetailed(code);
      
      expect(results.length).toBeGreaterThan(1);
      results.forEach(r => {
        expect(r).toHaveProperty('type');
        expect(r).toHaveProperty('description');
      });
    });

    it('should return empty array when no patterns match', () => {
      const code = "import React from 'react';";
      
      const results = detector.detectDetailed(code);
      
      expect(results).toHaveLength(0);
    });
  });

  describe('isFromSandbox', () => {
    it('should return true for matching sandbox', () => {
      const code = "import { create } from '@google/generative-ai';";
      
      expect(detector.isFromSandbox(code, 'ai-studio')).toBe(true);
      expect(detector.isFromSandbox(code, 'bolt.new')).toBe(false);
      expect(detector.isFromSandbox(code, 'replit')).toBe(false);
    });

    it('should return false for unknown code', () => {
      const code = "import React from 'react';";
      
      expect(detector.isFromSandbox(code, 'ai-studio')).toBe(false);
      expect(detector.isFromSandbox(code, 'bolt.new')).toBe(false);
    });
  });

  describe('getConfidence', () => {
    it('should return high confidence for single sandbox', () => {
      const code = "import { create } from '@google/generative-ai';";
      
      const confidence = detector.getConfidence(code, 'ai-studio');
      
      expect(confidence).toBeGreaterThan(0.5);
    });

    it('should return 0 for non-matching sandbox', () => {
      const code = "import { create } from '@google/generative-ai';";
      
      const confidence = detector.getConfidence(code, 'bolt.new');
      
      expect(confidence).toBe(0);
    });

    it('should return 0.5 for unknown with no patterns', () => {
      const code = "import React from 'react';";
      
      const confidence = detector.getConfidence(code, 'unknown');
      
      expect(confidence).toBe(0.5);
    });

    it('should handle mixed code correctly', () => {
      const code = `
        import { create } from '@google/generative-ai';
        // bolt.new reference
      `;
      
      const aiStudioConfidence = detector.getConfidence(code, 'ai-studio');
      const boltConfidence = detector.getConfidence(code, 'bolt.new');
      
      expect(aiStudioConfidence).toBeGreaterThan(0);
      expect(boltConfidence).toBeGreaterThan(0);
    });
  });

  describe('getPatternsForType', () => {
    it('should return patterns for AI Studio', () => {
      const patterns = detector.getPatternsForType('ai-studio');
      
      expect(Array.isArray(patterns)).toBe(true);
      expect(patterns.length).toBeGreaterThan(0);
      patterns.forEach(p => {
        expect(p.type).toBe('ai-studio');
      });
    });

    it('should return empty array for unknown type', () => {
      const patterns = detector.getPatternsForType('unknown' as any);
      
      expect(Array.isArray(patterns)).toBe(true);
      expect(patterns).toHaveLength(0);
    });

    it('should return patterns for Bolt.new', () => {
      const patterns = detector.getPatternsForType('bolt.new');
      
      expect(Array.isArray(patterns)).toBe(true);
      expect(patterns.length).toBeGreaterThan(0);
      patterns.forEach(p => {
        expect(p.type).toBe('bolt.new');
      });
    });

    it('should return patterns for Replit', () => {
      const patterns = detector.getPatternsForType('replit');
      
      expect(Array.isArray(patterns)).toBe(true);
      expect(patterns.length).toBeGreaterThan(0);
      patterns.forEach(p => {
        expect(p.type).toBe('replit');
      });
    });
  });

  describe('addPattern', () => {
    it('should add custom pattern', () => {
      const customPattern = {
        pattern: /custom-sandbox/i,
        type: 'custom-sandbox' as const,
        description: 'Custom sandbox',
      };
      
      detector.addPattern(customPattern);
      
      const code = "// custom-sandbox reference";
      const type = detector.detect(code);
      
      expect(type).toBe('custom-sandbox');
    });
  });

  describe('clearPatterns', () => {
    it('should clear all patterns', () => {
      const code = "import { create } from '@google/generative-ai';";
      
      // First, verify detection works
      expect(detector.detect(code)).toBe('ai-studio');
      
      // Clear patterns
      detector.clearPatterns();
      
      // Now it should return unknown
      expect(detector.detect(code)).toBe('unknown');
    });
  });

  describe('getPatterns', () => {
    it('should return all patterns', () => {
      const patterns = detector.getPatterns();
      
      expect(Array.isArray(patterns)).toBe(true);
      expect(patterns.length).toBeGreaterThan(0);
      patterns.forEach(p => {
        expect(p).toHaveProperty('pattern');
        expect(p).toHaveProperty('type');
        expect(p).toHaveProperty('description');
        expect(p.pattern).toBeInstanceOf(RegExp);
        expect(typeof p.type).toBe('string');
        expect(typeof p.description).toBe('string');
      });
    });

    it('should include patterns for all sandboxes', () => {
      const patterns = detector.getPatterns();
      const types = new Set(patterns.map(p => p.type));
      
      expect(types.has('ai-studio')).toBe(true);
      expect(types.has('bolt.new')).toBe(true);
      expect(types.has('replit')).toBe(true);
      expect(types.has('codesandbox')).toBe(true);
      expect(types.has('stackblitz')).toBe(true);
    });
  });
});