/**
 * Sandbox Detector
 * 
 * Detects AI sandbox environment from code patterns
 */

import { logger } from '../logger.js';

export type SandboxType =
  | 'ai-studio'
  | 'bolt.new'
  | 'replit'
  | 'codesandbox'
  | 'stackblitz'
  | 'unknown';

export interface SandboxPattern {
  /** Regular expression pattern to match */
  pattern: RegExp;
  /** Type of sandbox */
  type: SandboxType;
  /** Description of pattern */
  description: string;
}

export interface SandboxDetectionResult {
  /** Type of sandbox */
  type: SandboxType;
  /** Description of detection */
  description: string;
}

/**
 * Default sandbox patterns to detect
 */
const DEFAULT_SANDBOX_PATTERNS: SandboxPattern[] = [
  // AI Studio patterns
  {
    pattern: /@google\/generative-ai/i,
    type: 'ai-studio',
    description: 'Google AI Studio - detected from @google/generative-ai import',
  },
  {
    pattern: /@google\/ai-protos/i,
    type: 'ai-studio',
    description: 'Google AI Studio - detected from @google/ai-protos import',
  },
  {
    pattern: /\bgemini\b/i,
    type: 'ai-studio',
    description: 'Google AI Studio - detected from Gemini reference',
  },
  {
    pattern: /google\.ai\.generativelanguage/i,
    type: 'ai-studio',
    description: 'Google AI Studio - detected from google.ai.generativelanguage API',
  },

  // Bolt.new patterns
  {
    pattern: /bolt\.new/i,
    type: 'bolt.new',
    description: 'Bolt.new - detected from bolt.new reference',
  },
  {
    pattern: /generated by bolt/i,
    type: 'bolt.new',
    description: 'Bolt.new - detected from comment',
  },

  // Replit patterns
  {
    pattern: /@replit\//i,
    type: 'replit',
    description: 'Replit - detected from @replit package',
  },
  {
    pattern: /replit\/auth/i,
    type: 'replit',
    description: 'Replit - detected from replit/auth import',
  },

  // CodeSandbox patterns
  {
    pattern: /codesandbox/i,
    type: 'codesandbox',
    description: 'CodeSandbox - detected from codesandbox reference',
  },

  // StackBlitz patterns
  {
    pattern: /stackblitz/i,
    type: 'stackblitz',
    description: 'StackBlitz - detected from stackblitz reference',
  },
];

export class SandboxDetector {
  private readonly patterns: SandboxPattern[];
  private readonly logger = logger.child('SandboxDetector');

  constructor(patterns: SandboxPattern[] = DEFAULT_SANDBOX_PATTERNS) {
    this.patterns = [...patterns];
    this.logger.debug(`Initialized with ${patterns.length} patterns`);
  }

  /**
   * Detect sandbox type from code
   * Returns first matching sandbox type, or 'unknown' if no pattern matches
   */
  detect(code: string): SandboxType {
    const detected = this.detectAll(code);
    
    if (detected.length === 0) {
      return 'unknown';
    }

    return detected[0];
  }

  /**
   * Detect all possible sandbox types from code
   */
  detectAll(code: string): SandboxType[] {
    const detectedTypes = new Set<SandboxType>();

    for (const { pattern, type } of this.patterns) {
      if (pattern.test(code)) {
        detectedTypes.add(type);
        this.logger.debug(`Detected sandbox: ${type}`);
      }
    }

    const types = Array.from(detectedTypes);
    if (types.length === 0) {
      return ['unknown'];
    }

    return types;
  }

  /**
   * Detect sandbox with detailed results
   */
  detectDetailed(code: string): SandboxDetectionResult[] {
    const results: SandboxDetectionResult[] = [];

    for (const { pattern, type, description } of this.patterns) {
      if (pattern.test(code)) {
        results.push({ type, description });
        this.logger.debug(`Detected sandbox: ${type} - ${description}`);
      }
    }

    return results;
  }

  /**
   * Check if code is from a specific sandbox
   */
  isFromSandbox(code: string, sandboxType: SandboxType): boolean {
    if (sandboxType === 'unknown') {
      return this.detectAll(code).length === 0;
    }

    const patterns = this.getPatternsForType(sandboxType);
    for (const { pattern } of patterns) {
      if (pattern.test(code)) {
        return true;
      }
    }
    return false;
  }

  /**
   * Get confidence score for a sandbox type (0-1)
   */
  getConfidence(code: string, sandboxType: SandboxType): number {
    if (sandboxType === 'unknown') {
      const detectedTypes = this.detectAll(code);
      // If detectAll returns only 'unknown' or empty, confidence is 0.5
      return (detectedTypes.length === 0 || (detectedTypes.length === 1 && detectedTypes[0] === 'unknown')) ? 0.5 : 0;
    }

    const patterns = this.getPatternsForType(sandboxType);
    let matchCount = 0;

    for (const { pattern } of patterns) {
      if (pattern.test(code)) {
        matchCount++;
      }
    }

    if (patterns.length === 0) return 0;

    // Confidence based on proportion of matching patterns
    // If at least one pattern matches, give it decent confidence
    if (matchCount > 0) {
      const baseConfidence = 0.7; // Base confidence for any match
      const bonusConfidence = (matchCount / patterns.length) * 0.3; // Bonus for more matches
      return Math.min(1.0, baseConfidence + bonusConfidence);
    }

    return 0;
  }

  /**
   * Get all patterns for a specific sandbox type
   */
  getPatternsForType(sandboxType: SandboxType): SandboxPattern[] {
    return this.patterns.filter(p => p.type === sandboxType);
  }

  /**
   * Add a custom sandbox pattern
   */
  addPattern(pattern: SandboxPattern): void {
    this.patterns.push(pattern);
    this.logger.debug(`Added pattern for: ${pattern.type}`);
  }

  /**
   * Remove all patterns
   */
  clearPatterns(): void {
    this.patterns.length = 0;
    this.logger.debug('Cleared all patterns');
  }

  /**
   * Get all current patterns
   */
  getPatterns(): SandboxPattern[] {
    return [...this.patterns];
  }
}

/**
 * Create a default SandboxDetector instance
 */
export function createSandboxDetector(): SandboxDetector {
  return new SandboxDetector();
}