/**
 * ProjectGenerator - Orchestrates complete project scaffolding
 *
 * Generates a production-ready project structure from transformation results,
 * including package.json, tsconfig.json, README, and all source files.
 *
 * @module generators/ProjectGenerator
 */

import { join } from 'path';
import { mkdir, writeFile } from 'fs/promises';
import { TemplateEngine } from './TemplateEngine.js';

import { FileSystemError } from '../errors.js';
import { logger } from '../logger.js';
import type { ProjectStructure, EscapeContract } from '../models/transformation.js';

/** Parameters for project generation */
export interface GeneratorParams {
  /** Root output directory */
  rootPath: string;
  /** Project name */
  projectName: string;
  /** Project description */
  description?: string;
  /** Project version */
  version?: string;
  /** Author name */
  author?: string;
  /** License */
  license?: string;
  /** Target deployment platform */
  targetPlatform?: string;
  /** Resolved dependencies (name → version) */
  dependencies?: Map<string, string>;
  /** Escape contract to embed */
  escapeContract?: EscapeContract;
  /** Include Dockerfile */
  includeDocker?: boolean;
  /** Include CI/CD workflow */
  includeCI?: boolean;
  /** Custom template directory */
  templatePath?: string;
  /** Node.js version requirement */
  nodeVersion?: string;
}

/**
 * Orchestrates complete project generation.
 *
 * @example
 * ```typescript
 * const generator = new ProjectGenerator();
 * const structure = await generator.generate({
 *   rootPath: '/output/my-project',
 *   projectName: 'my-project',
 *   dependencies: new Map([['axios', '^1.6.0']]),
 * });
 * ```
 */
export class ProjectGenerator {
  private readonly templateEngine: TemplateEngine;
  private readonly log = logger.child('ProjectGenerator');

  constructor() {
    this.templateEngine = new TemplateEngine();
  }

  /**
   * Generate a complete project structure.
   */
  async generate(params: GeneratorParams): Promise<ProjectStructure> {
    const {
      rootPath,
      projectName,
      description = 'Generated by EscapeKit MCP',
      version = '1.0.0',
      author = '',
      license = 'MIT',
      targetPlatform = 'local',
      dependencies = new Map<string, string>(),
      escapeContract,
      includeDocker = false,
      includeCI = false,
      nodeVersion = '18.0.0',
    } = params;

    this.log.info('Generating project', { rootPath, projectName });

    const dirs = ['src', 'tests', 'public', 'config'];
    const files = new Map<string, string>();

    // Create directories
    await this.createDirectories(rootPath, dirs);

    // Template context
    const ctx: Record<string, unknown> = {
      projectName,
      description,
      version,
      author,
      license,
      targetPlatform,
      nodeVersion,
      includeDocker,
      includeCI,
      dependencies: Object.fromEntries(dependencies),
    };

    // package.json
    const pkgJson = this.generatePackageJson({ ...params, dependencies });
    files.set('package.json', JSON.stringify(pkgJson, null, 2));

    // tsconfig.json
    const tsConfig = this.generateTsConfig();
    files.set('tsconfig.json', JSON.stringify(tsConfig, null, 2));

    // README.md
    try {
      const readmeTpl = await this.templateEngine.loadTemplate('templates/README.md.hbs');
      files.set('README.md', this.templateEngine.render(readmeTpl, ctx));
    } catch {
      files.set('README.md', `# ${projectName}\n\n${description}\n`);
    }

    // .gitignore
    try {
      const gitignoreTpl = await this.templateEngine.loadTemplate('templates/.gitignore.hbs');
      files.set('.gitignore', this.templateEngine.render(gitignoreTpl, ctx));
    } catch {
      files.set('.gitignore', 'node_modules/\ndist/\n.env\n');
    }

    // Dockerfile (optional)
    if (includeDocker) {
      try {
        const dockerTpl = await this.templateEngine.loadTemplate('templates/Dockerfile.hbs');
        files.set('Dockerfile', this.templateEngine.render(dockerTpl, { ...ctx, port: 3000 }));
      } catch {
        // Skip if template not found
      }
    }

    // CI workflow (optional)
    if (includeCI) {
      try {
        const ciTpl = await this.templateEngine.loadTemplate('templates/.github/workflows/ci.yml.hbs');
        files.set('.github/workflows/ci.yml', this.templateEngine.render(ciTpl, ctx));
      } catch {
        // Skip if template not found
      }
    }

    // Escape contract
    if (escapeContract) {
      files.set('escape-contract.json', JSON.stringify(escapeContract, null, 2));
    }

    // Write all files
    await this.writeFiles(rootPath, files);

    this.log.info('Project generation complete', { rootPath, fileCount: files.size });

    return {
      rootPath,
      directories: dirs,
      files,
      dependencies,
      configuration: {
        packageJson: pkgJson,
        tsConfig,
      },
    };
  }

  /**
   * Create project directories.
   */
  async createDirectories(rootPath: string, dirs: string[]): Promise<void> {
    try {
      await mkdir(rootPath, { recursive: true });
      for (const dir of dirs) {
        await mkdir(join(rootPath, dir), { recursive: true });
      }
    } catch (err) {
      throw new FileSystemError(
        `Failed to create directories: ${(err as Error).message}`,
        'mkdir',
        { path: rootPath }
      );
    }
  }

  /**
   * Generate package.json content.
   */
  generatePackageJson(params: GeneratorParams): Record<string, unknown> {
    const deps: Record<string, string> = {};
    if (params.dependencies) {
      for (const [name, version] of params.dependencies) {
        deps[name] = version;
      }
    }

    return {
      name: params.projectName.toLowerCase().replace(/\s+/g, '-'),
      version: params.version ?? '1.0.0',
      description: params.description ?? '',
      type: 'module',
      main: 'dist/index.js',
      scripts: {
        build: 'tsc',
        dev: 'tsx watch src/index.ts',
        start: 'node dist/index.js',
        test: 'vitest --run',
        lint: 'eslint src --ext .ts',
      },
      dependencies: deps,
      devDependencies: {
        '@types/node': '^20.11.0',
        typescript: '^5.3.3',
        tsx: '^4.7.0',
        vitest: '^1.2.0',
      },
      engines: {
        node: `>=${params.nodeVersion ?? '18.0.0'}`,
      },
      author: params.author ?? '',
      license: params.license ?? 'MIT',
    };
  }

  /**
   * Generate tsconfig.json content.
   */
  generateTsConfig(): Record<string, unknown> {
    return {
      compilerOptions: {
        target: 'ES2020',
        module: 'ESNext',
        moduleResolution: 'bundler',
        lib: ['ES2020', 'DOM'],
        outDir: 'dist',
        rootDir: 'src',
        strict: true,
        esModuleInterop: true,
        allowSyntheticDefaultImports: true,
        skipLibCheck: true,
        forceConsistentCasingInFileNames: true,
        declaration: true,
        sourceMap: true,
        resolveJsonModule: true,
      },
      include: ['src/**/*'],
      exclude: ['node_modules', 'dist', '**/*.test.ts'],
    };
  }

  /**
   * Write all files to disk.
   */
  async writeFiles(rootPath: string, files: Map<string, string>): Promise<void> {
    for (const [relativePath, content] of files) {
      const fullPath = join(rootPath, relativePath);
      const dir = fullPath.substring(0, fullPath.lastIndexOf('/'));
      try {
        await mkdir(dir, { recursive: true });
        await writeFile(fullPath, content, 'utf-8');
      } catch (err) {
        throw new FileSystemError(
          `Failed to write file "${fullPath}": ${(err as Error).message}`,
          'writeFile',
          { path: fullPath }
        );
      }
    }
  }
}
