import * as core from '@actions/core';
import * as github from '@actions/github';
import { CheckResult } from './CheckRunner';
import * as crypto from 'crypto';

export class PRCommentBuilder {
  async postComment(result: CheckResult): Promise<void> {
    const octokit = github.getOctokit(core.getInput('github-token'));
    
    const comment = this.buildComment(result);
    
    await octokit.rest.issues.createComment({
      ...github.context.repo,
      issue_number: github.context.payload.pull_request?.number || 0,
      body: comment
    });
  }
  
  private buildComment(result: CheckResult): string {
    const reportHash = this.generateReportHash(result);
    
    return `## CodeMemória Compliance Report

${this.renderBadge(result.riskLevel)}

**Risk Level**: ${result.riskLevel.toUpperCase()}

**Files Analyzed**: ${result.fileResults.length}

**Findings**:
${result.fileResults.map(f => 
      `- ${f.filePath}: ${f.riskLevel} (${f.validationCount} findings)`
    ).join('\n')}

**Report Hash**: ${reportHash}

_Generated by [CodeMemória](${process.env.GITHUB_SERVER_URL || 'https://github.com'}/${process.env.GITHUB_REPOSITORY || ''})_`;
  }
  
  private renderBadge(riskLevel: string): string {
    const color = {
      critical: 'red',
      high: 'orange',
      medium: 'yellow',
      low: 'green'
    }[riskLevel] || 'grey';
    
    return `![${riskLevel} risk](https://img.shields.io/badge/risk-${riskLevel}-${color})`;
  }
  
  private generateReportHash(result: CheckResult): string {
    const hash = crypto.createHash('sha256');
    hash.update(JSON.stringify(result.passports));
    return hash.digest('hex');
  }
}